name: CI/CD Pipeline

# Ejecutar el pipeline en los eventos push o pull request en la rama 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Etapa 1: Build (Construcción del proyecto)
  build:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Java (JDK 17)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Cambia a la versión que uses
          distribution: 'temurin'

      # Paso 3: Construir el proyecto con Maven
      - name: Build with Maven
        run: mvn compile

  # Etapa 2: Test (Ejecutar pruebas unitarias)
  test:
    runs-on: ubuntu-latest
    needs: build  # Depende de la etapa build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn test

  # Etapa 3: Deploy (Simular despliegue)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Depende de la etapa test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deployment
        run: zip -r deploy-package.zip target/
